---@class WowUkrainizerInternals
---@field CommonUtil CommonUtil
---@field FontStringUtil FontStringUtil
---@field StringUtil StringUtil
---@field CommonData CommonData
---@field PlayerData PlayerData
---@field EventHandlerFactory EventHandlerFactory
