---@meta

---@alias UIFrameType
---|"Spellbook"
---|"ClassTalent"
---|"Main"
---|"Quest"

---@alias ChangelogEntryColor
---|"purple"
---|"blue"
---|"red"
---|"green"

---@class WowUkrainizerInternals
---@field private _settingsProvider SettingsProvider? @Singleton instance of the SettingsProvider.
---@field private _untranslatedDataStorage UntranslatedDataStorage? @Singleton instance of the UntranslatedDataStorage.

---@class (exact) TranslatedQuestData
---@field ID number The unique identifier of the quest.
---@field Title string The translated title of the quest.
---@field Description string The translated description of the quest.
---@field ObjectivesText string The translated text describing the quest objectives.
---@field ContainsObjectives boolean Indicates whether the quest contains specific objectives.
---@field CompletionText string The translated text displayed upon quest completion.
---@field TargetName string The translated name of the quest target.
---@field TargetDescription string The translated description of the quest target.
---@field TargetCompletedName string The translated name of the quest target upon completion.
---@field TargetCompletedDescription string The translated description of the quest target upon completion.
---@field AreaDescription string The translated description of the quest area.
---@field RewardText string The translated text describing the quest rewards.
---@field ProgressText string The translated text describing quest progress.
---@field IsMtData boolean True if any translated text generated by AI; otherwise false

--- Changelog entry containing details of each change.
---@class ChangelogEntry
---@field version string -- The version the change was made in
---@field date string -- The date the change was made
---@field color ChangelogEntryColor -- Color code for UI display
---@field type string -- The type of change
---@field author string -- The author who made the change
---@field title string? -- The title summarizing the change
---@field description string -- Full description of the change

---@class (exact) WowUkrainizerDatabase
---@field Changelogs ChangelogEntry[] Array of changelog entries, newest first
---@field MTQuests table<integer, string[]>
---@field MTQuestObjectives table<integer, table<integer, string>>
