-- Colors

WOW_UKRAINIZER_WHITE_COLOR = { r = 1, g = 1, b = 1 }
WOW_UKRAINIZER_GREEN_COLOR = { r = 0.271, g = 0.561, b = 0.094 }
WOW_UKRAINIZER_DISABLED_COLOR = { r = 0.427, g = 0.443, b = 0.478 }
WOW_UKRAINIZER_SECONDARY_TEXT_COLOR = { r = 0.604, g = 0.592, b = 0.725 }

-- Settings Options

WOW_UKRAINIZER_MAIN_FONT_NAME_OPTION = "MainFontName"
WOW_UKRAINIZER_TITLE_FONT_NAME_OPTION = "TitleFontName"
WOW_UKRAINIZER_TOOLTIP_FONT_NAME_OPTION = "TooltipFontName"

WOW_UKRAINIZER_TRANSLATE_CLASS_TALENTS_FRAME_OPTION = "TranslateClassTalentsFrame"
WOW_UKRAINIZER_TRANSLATE_SPELLBOOK_FRAME_OPTION = "TranslateSpellbookFrame"
WOW_UKRAINIZER_TRANSLATE_QUEST_AND_OBJECTIVES_FRAME_OPTION = "TranslateQuestAndObjectivesFrame"
WOW_UKRAINIZER_DISABLE_MT_FOR_QUESTS_OPTION = "DisableMTForTranslateQuestAndObjectivesFrame"
WOW_UKRAINIZER_TRANSLATE_QUEST_TEXT_OPTION = "TranslateQuestText"
WOW_UKRAINIZER_TRANSLATE_NAMEPLATES_AND_UNIT_FRAMES_OPTION = "TranslateNameplatesAndUnitFrames"
WOW_UKRAINIZER_SPELL_NAME_LANG_IN_SPELLBOOK_OPTION = "SpellNameLangInSpellbook"
WOW_UKRAINIZER_TRANSLATE_SUBTITLES_OPTION = "TranslateSubtitles"
WOW_UKRAINIZER_TRANSLATE_NPC_MESSAGES_OPTION = "TranslateNpcMessages"
WOW_UKRAINIZER_TRANSLATE_UNIT_TOOLTIPS_OPTION = "TranslateUnitTooltips"
WOW_UKRAINIZER_TRANSLATE_ZONE_TEXTS_OPTION = "TranslateZoneTexts"
WOW_UKRAINIZER_TRANSLATE_MAP_AND_QUEST_LOG_FRAME_OPTION = "TranslateMapAndQuestLogFrame"
WOW_UKRAINIZER_TRANSLATE_CHARACTER_FRAME_OPTION = "TranslateCharacterFrame"

WOW_UKRAINIZER_HIGHLIGHT_SPELL_NAME_IN_DESCRIPTION_OPTION = "HighlightSpellNameInDescription"
WOW_UKRAINIZER_TRANSLATE_SPELL_TOOLTIPS_OPTION = "TranslateSpellTooltips"
WOW_UKRAINIZER_TOOLTIP_SPELL_LANG_IN_NAME_OPTION = "TooltipSpellLangInName"
WOW_UKRAINIZER_TOOLTIP_SPELL_LANG_IN_DESCRIPTION_OPTION = "TooltipSpellLangInDescription"
WOW_UKRAINIZER_TRANSLATE_ITEM_TOOLTIPS_OPTION = "TranslateItemTooltips"
WOW_UKRAINIZER_DO_NOT_TRANSLATE_ITEM_NAME_OPTION = "DoNotTranslateItemNameButton"
WOW_UKRAINIZER_DO_NOT_TRANSLATE_ITEM_ATTRIBUTES_OPTION = "DoNotTranslateItemAttributesButton"

WOW_UKRAINIZER_IS_FIRST_RUN_OPTION = "IsFirstRun"
WOW_UKRAINIZER_LAST_AUTO_SHOWN_CHANGELOG_VERSION_OPTION = "LastAutoShownChangelogVersion"

WOW_UKRAINIZER_MAIN_FONT_SCALE_IN_PERCENT_OPTION = "FontScaleInPercent"
WOW_UKRAINIZER_TITLE_FONT_SCALE_IN_PERCENT_OPTION = "TitleFontScaleInPercent"
WOW_UKRAINIZER_TOOLTIP_FONT_SCALE_IN_PERCENT_OPTION = "TooltipFontScaleInPercent"
WOW_UKRAINIZER_USE_DEFAULT_FONTS_OPTION = "UseDefaultFonts"
WOW_UKRAINIZER_USE_ADAPTED_FONTS_OPTION = "UseAdaptedFonts"
WOW_UKRAINIZER_USE_CUSTOMIZED_FONTS_OPTION = "UseCustomizedFonts"
WOW_UKRAINIZER_ADAPTED_MAIN_FONT_NAME = "Friz Quadrata TT (укр.)"
WOW_UKRAINIZER_ADAPTED_MAIN_FONT_PATH = [[Interface\AddOns\WowUkrainizer\assets\Classic_UA_FRIZQT.ttf]]
WOW_UKRAINIZER_ADAPTED_TITLE_FONT_NAME = "Morpheus (укр.)"
WOW_UKRAINIZER_ADAPTED_TITLE_FONT_PATH = [[Interface\AddOns\WowUkrainizer\assets\Classic_UA_Morpheus.ttf]]
