--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

local _, ns = ...;

if (not ns._db) then return end

ns._db.SpellbookFrameLines = {
	[3180667627] = "Вихованець",
	[1447821407] = "Професії",
	[1381116717] = "Книга здібностей",
	[220936074] = "На цих вкладках ви можете побачити всі заклинання, які ви отримаєте, якщо зміните свою спеціалізацію.\n\nДеякі з них будуть доступні у декількох спеціалізаціях.",
	[3431194032] = "На цих вкладках відображаються ваші поточні заклинання.",
	[2427698666] = "Перетягніть заклинання на панель дії.  Спочатку відображаються ваші активні заклинання, а потім пасивні.",
}

