--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

--- @class WowUkrainizerInternals
local ns = select(2, ...);

if (not ns._db) then return end

ns._db.GlobalStrings = {
	[3482464984] = "(Святилище)",
	[2208357618] = "(Зона PvP)",
	[2103687266] = "(Спірна територія)",
	[3972179574] = "(Зона бойових дій)",
	[1347341965] = "Ви слідуєте за %s",
	[2768828709] = "Ви припиняєте слідувати за %s",
	[2396301741] = "(Територія %s)",
	[2489616146] = "Карта світу",
	[3503056421] = "Світ",
	[915482299] = "Карта та журнал завдань",
	[3081121488] = "Карта",
	[2304996567] = "Рівень улюбленців",
	[178388956] = "Відкрито нову місцевість!",
	[1303995339] = "Відкрито: %s. Отримано %d досвіду.",
	[2853461421] = "Відкрито: %s",
	[3184911835] = "Рейд",
	[1913653597] = "Підземелля",
}

