--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

--- @class WowUkrainizerInternals
local ns = select(2, ...);

if (not ns._db) then return end

ns._db.GlobalStrings = {
    [3482464984] = "(Прихисток)",
    [2208357618] = "(Зона PvP)",
    [2103687266] = "(Оспорювана територія)",
    [3972179574] = "(Зона бойових дій)",
    [1347341965] = "Слідую за %s",
    [2768828709] = "Ти припиняєш слідувати за %s",
    [2396301741] = "(Територія %s)",
}
