local _, ns = ...;

-- Constants
ns.FACTION_ALLIANCE = "Альянс"
ns.FACTION_HORDE = "Орда"

ns.LEVEL_TRANSLATION = "Рівень"
ns.PAGE_TRANSLATION = "Сторінка"
ns.LEADER_TRANSLATION = "Ватажок"

ns.SPELL_GENERAL_TRANSLATION = "Загальні"
ns.SPELL_PASSIVE_TRANSLATION = "Пасивний"
ns.SPELL_RANK_TRANSLATION = "Pівень"
ns.SPELL_NEXT_RANK_TRANSLATION = "Наступний рівень:"

ns.TALENT_REPLACES_TRANSLATION = "Замінює"
ns.TALENT_REPLACED_BY_TRANSLATION = "Замінено на"
ns.TALENT_UPGRADE_TRANSLATION = "Оновлення"

ns.PET_LEVEL_TRANSLATION = "Супутник {1} рівня"
ns.PET_CAPTURABLE_TRANSLATION = "Mожна приручити"
ns.PET_COLLECTED_TRANSLATION = "Зібрано ({1}/{2})"

ns.QUEST_TITLE = 1
ns.QUEST_DESCRIPTION = 2
ns.QUEST_OBJECTIVES_TEXT = 3
ns.QUEST_TARGET_NAME = 4
ns.QUEST_TARGET_DESCRIPTION = 5
ns.QUEST_LOG_COMPLETION_TEXT = 6
ns.QUEST_PROGRESS_TEXT = 7
ns.QUEST_COMPLETED_TEXT = 8

ns._db = {}
