--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

--- @class WowUkrainizerInternals
local ns = select(2, ...);

if (not ns._db) then return end

ns._db.ItemAttributes = {
	[503660382] = "Сила",
	[1625811594] = "Інтелект",
	[2954854313] = "Спритність",
	[3986999497] = "Броня",
	[2366160346] = "Міцність",
	[2375685100] = "Критичний удар",
	[1930377443] = "Швидкість",
	[815347557] = "Майстерність",
	[3909808918] = "Універсальність",
	[247433944] = "Швидкість",
	[3982637038] = "Самозцілення",
	[1507206193] = "Уникнення",
	[106082565] = "Парирування",
	[2289139729] = "Ухилення",
	[834022333] = "Незнищенний",
	[3760460996] = "Дух",
	[228425106] = "Швидкість пересування",
	[422384902] = "Витривалість",
}

