--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]
local _, ns = ...;

if (not ns._db) then return end

do
    local data = {
        [1292786250] = "Остін Хаксворт", -- Austin Huxworth (id: 157046, 154327, 156610, 161666)
    }

    ns._db.UnitNames = data
end

do
    local data = {
        [2989914850] = "Конюший", -- Stable Master
    }

    ns._db.UnitSubnames = data
end
