--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

local _, ns = ...;

local voiceOverData = {}

voiceOverData.Cinematics = {
	[1844457017] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152835_3486924.ogg]], lengthInSeconds = 9.71 },
	[3664374311] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152836_3486925.ogg]], lengthInSeconds = 6.19 },
	[1815550003] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152837_3486926.ogg]], lengthInSeconds = 6.01 },
	[2556975142] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152845_3486934.ogg]], lengthInSeconds = 7.53 },
	[706583598] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_156812_3584836.ogg]], lengthInSeconds = 10.86 },
	[2768331800] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_161221_3636985.ogg]], lengthInSeconds = 6.83 },
	[2448792133] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_161222_3636986.ogg]], lengthInSeconds = 6.43 },
	[2713478487] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_161223_3636987.ogg]], lengthInSeconds = 6.38 },
}


voiceOverData.Dialogs = {
	[2598535587] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152731_3485456.ogg]], lengthInSeconds = 3.55 },
	[1922980967] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152732_3485457.ogg]], lengthInSeconds = 6.05 },
	[1090448917] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152718_3485443.ogg]], lengthInSeconds = 5.95 },
	[1929738606] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152734_3485459.ogg]], lengthInSeconds = 5.29 },
	[3687745317] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152846_3486957.ogg]], lengthInSeconds = 2.81 },
	[1655187725] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152847_3486958.ogg]], lengthInSeconds = 3.56 },
	[2911821392] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152897_3488623.ogg]], lengthInSeconds = 1.69 },
	[4229072475] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152848_3486959.ogg]], lengthInSeconds = 5.21 },
	[372028375] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152849_3486966.ogg]], lengthInSeconds = 2.83 },
	[1592247642] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152735_3485460.ogg]], lengthInSeconds = 1.77 },
	[2930961147] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152736_3485461.ogg]], lengthInSeconds = 3.24 },
	[2014878743] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156949_3586023.ogg]], lengthInSeconds = 3.94 },
	[214564778] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156950_3586024.ogg]], lengthInSeconds = 8.02 },
	[189554568] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156951_3586025.ogg]], lengthInSeconds = 7.19 },
	[4153089120] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156952_3586026.ogg]], lengthInSeconds = 5.33 },
	[3743913128] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156973_3586095.ogg]], lengthInSeconds = 4.55 },
	[2374790243] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156974_3586096.ogg]], lengthInSeconds = 3.48 },
	[122125822] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156975_3586097.ogg]], lengthInSeconds = 2.18 },
	[3051315049] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156976_3586098.ogg]], lengthInSeconds = 6.13 },
	[2623088084] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156977_3586099.ogg]], lengthInSeconds = 3.72 },
	[4279207447] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156953_3586027.ogg]], lengthInSeconds = 1.93 },
	[1466862686] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156954_3586028.ogg]], lengthInSeconds = 4.81 },
	[592587531] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_152858_3486994.ogg]], lengthInSeconds = 4.68 },
	[4201528573] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\vo_152854_3486982.ogg]], lengthInSeconds = 2.12 },
	[2881130621] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\vo_152857_3486991.ogg]], lengthInSeconds = 3.07 },
	[604366029] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\vo_152850_3486969.ogg]], lengthInSeconds = 3.12 },
	[2195208358] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\vo_152851_3486970.ogg]], lengthInSeconds = 4.5 },
	[3433526274] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\vo_152852_3486971.ogg]], lengthInSeconds = 4.46 },
	[4229318943] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\vo_152855_3486983.ogg]], lengthInSeconds = 4.24 },
	[3081143028] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\vo_152920_3488692.ogg]], lengthInSeconds = 3.33 },
	[136293607] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\vo_152921_3488693.ogg]], lengthInSeconds = 4.25 },
	[4072960736] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\vo_152856_3486984.ogg]], lengthInSeconds = 4.83 },
	[1633161835] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_153011_3488947.ogg]], lengthInSeconds = 2.66 },
	[2672549074] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_153012_3488948.ogg]], lengthInSeconds = 3.42 },
	[3020079399] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_153013_3488949.ogg]], lengthInSeconds = 3.54 },
	[168417599] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_153014_3488950.ogg]], lengthInSeconds = 4.41 },
	[2576202347] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_153015_3488951.ogg]], lengthInSeconds = 2.95 },
	[3430280186] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\vo_153016_3488952.ogg]], lengthInSeconds = 4.49 },
	[1925102631] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\vo_152962_3488806.ogg]], lengthInSeconds = 3.61 },
	[3820301923] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\vo_152963_3488807.ogg]], lengthInSeconds = 1.91 },
	[4105945012] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\vo_152964_3488808.ogg]], lengthInSeconds = 2.02 },
	[2183940547] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\vo_152965_3488809.ogg]], lengthInSeconds = 2.06 },
	[87485479] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156955_3586029.ogg]], lengthInSeconds = 7.86 },
	[1407848859] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\lana_jordan\vo_155934_3574371.ogg]], lengthInSeconds = 5.18 },
	[996734954] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\vo_156978_3586100.ogg]], lengthInSeconds = 3.59 },
	[1906288526] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\vo_156979_3586101.ogg]], lengthInSeconds = 3.69 },
	[1789811370] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156956_3586030.ogg]], lengthInSeconds = 5.83 },
	[604366029] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\vo_156957_3586031.ogg]], lengthInSeconds = 2.3 },
	[59830284] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156958_3586032.ogg]], lengthInSeconds = .83 },
	[2286361189] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\vo_156959_3586033.ogg]], lengthInSeconds = 3.55 },
	[1791634542] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156960_3586034.ogg]], lengthInSeconds = 4.03 },
	[470545567] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156961_3586035.ogg]], lengthInSeconds = 4.85 },
	[3925226213] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\vo_156962_3586036.ogg]], lengthInSeconds = 2.92 },
	[4247190381] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156963_3586037.ogg]], lengthInSeconds = 4.34 },
	[4275834405] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156964_3586038.ogg]], lengthInSeconds = 8.45 },
	[214347748] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156919_3585797.ogg]], lengthInSeconds = 3.09 },
	[1245466146] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156715_3584067.ogg]], lengthInSeconds = 4.83 },
	[4273887682] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156687_3584039.ogg]], lengthInSeconds = 11.08 },
	[687813409] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156688_3584040.ogg]], lengthInSeconds = 4.21 },
	[2600285423] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156689_3584041.ogg]], lengthInSeconds = 7.42 },
	[2200318469] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156690_3584042.ogg]], lengthInSeconds = 6.12 },
	[3909382948] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156691_3584043.ogg]], lengthInSeconds = 6.02 },
	[1956278357] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156700_3584052.ogg]], lengthInSeconds = 7.17 },
	[2231153033] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156701_3584053.ogg]], lengthInSeconds = 4.7 },
	[3664130309] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156702_3584054.ogg]], lengthInSeconds = 10.23 },
	[1693877061] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156703_3584055.ogg]], lengthInSeconds = 5.18 },
	[2003372965] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156704_3584056.ogg]], lengthInSeconds = 5.45 },
	[1604547173] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156705_3584057.ogg]], lengthInSeconds = 4.91 },
	[1664476125] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156706_3584058.ogg]], lengthInSeconds = 8.62 },
	[4114235125] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156707_3584059.ogg]], lengthInSeconds = 7.11 },
	[3968623954] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156708_3584060.ogg]], lengthInSeconds = 5.24 },
	[2983886607] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156709_3584061.ogg]], lengthInSeconds = 5.65 },
	[114313383] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156720_3584072.ogg]], lengthInSeconds = 6.42 },
	[1971466311] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156722_3584074.ogg]], lengthInSeconds = 6.84 },
	[808777773] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156723_3584075.ogg]], lengthInSeconds = 3.54 },
	[2746122029] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156725_3584077.ogg]], lengthInSeconds = 3.18 },
	[2940968853] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156726_3584078.ogg]], lengthInSeconds = 7.98 },
	[1049646104] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156729_3584081.ogg]], lengthInSeconds = 5.61 },
	[2366260958] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156730_3584082.ogg]], lengthInSeconds = 10.36 },
	[2022938503] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156731_3584083.ogg]], lengthInSeconds = 8.89 },
	[129162206] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156732_3584084.ogg]], lengthInSeconds = 2.13 },
	[152180890] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156733_3584085.ogg]], lengthInSeconds = 4.8 },
	[3428148615] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156734_3584086.ogg]], lengthInSeconds = 6.02 },
	[3476894363] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156735_3584087.ogg]], lengthInSeconds = 8.61 },
	[1870808709] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156737_3584089.ogg]], lengthInSeconds = 2.09 },
	[1085823189] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156718_3584070.ogg]], lengthInSeconds = 7.89 },
	[1800827584] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156714_3584066.ogg]], lengthInSeconds = 4.65 },
	[363773934] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156717_3584069.ogg]], lengthInSeconds = 4.96 },
	[4161015957] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156965_3586039.ogg]], lengthInSeconds = 9.52 },
	[548359317] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\vo_156966_3586040.ogg]], lengthInSeconds = 5.59 },
	[2634656225] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156967_3586041.ogg]], lengthInSeconds = 5.1 },
	[1358807062] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\vo_156980_3586102.ogg]], lengthInSeconds = 5.26 },
	[371392505] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\vo_156739_3584222.ogg]], lengthInSeconds = 3.69 },
	[2747343274] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\vo_156740_3584223.ogg]], lengthInSeconds = 3.99 },
	[758612313] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156968_3586042.ogg]], lengthInSeconds = 4.23 },
	[4271080230] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\vo_156981_3586103.ogg]], lengthInSeconds = 4.57 },
	[1318902499] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156969_3586043.ogg]], lengthInSeconds = 4.74 },
}


voiceOverData.Emotions = {
	[169702] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_01_169702_3488634.ogg]], lengthInSeconds = 1.13 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_02_169702_3488635.ogg]], lengthInSeconds = 1.5 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_03_169702_3488636.ogg]], lengthInSeconds = .99 }, },
	[169703] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_01_169703_3488637.ogg]], lengthInSeconds = 1.49 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_02_169703_3488638.ogg]], lengthInSeconds = 1.3 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_03_169703_3488639.ogg]], lengthInSeconds = 2.25 }, },
	[169704] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_01_169704_3488640.ogg]], lengthInSeconds = 2.23 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_02_169704_3488641.ogg]], lengthInSeconds = 3.58 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_03_169704_3488642.ogg]], lengthInSeconds = 1.99 }, },
	[154039] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_01_154039_3485447.ogg]], lengthInSeconds = 2.65 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_02_154039_3485448.ogg]], lengthInSeconds = 1.87 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_03_154039_3485449.ogg]], lengthInSeconds = 1.79 }, },
	[154036] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_01_154036_3489790.ogg]], lengthInSeconds = .84 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_02_154036_3489791.ogg]], lengthInSeconds = 1.27 }, },
	[154040] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154040_3485450.ogg]], lengthInSeconds = 2 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154040_3485451.ogg]], lengthInSeconds = 2.35 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_03_154040_3485452.ogg]], lengthInSeconds = 2.11 }, },
	[154037] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154037_3489792.ogg]], lengthInSeconds = 1.91 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154037_3489793.ogg]], lengthInSeconds = 1.73 }, },
	[154038] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154038_3485444.ogg]], lengthInSeconds = 3.49 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154038_3485445.ogg]], lengthInSeconds = 2.71 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_03_154038_3485446.ogg]], lengthInSeconds = 1.76 }, },
	[154041] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_01_154041_3485453.ogg]], lengthInSeconds = 3.76 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_02_154041_3485454.ogg]], lengthInSeconds = 3.76 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_03_154041_3485455.ogg]], lengthInSeconds = 5.31 }, },
	[163362] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\farewells_01_163362_3585731.ogg]], lengthInSeconds = .96 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\farewells_02_163362_3585732.ogg]], lengthInSeconds = 1.28 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\farewells_03_163362_3585733.ogg]], lengthInSeconds = 2.38 }, },
	[163361] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\greetings_01_163361_3585734.ogg]], lengthInSeconds = 1.6 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\greetings_02_163361_3585735.ogg]], lengthInSeconds = 1.97 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\greetings_03_163361_3585736.ogg]], lengthInSeconds = 2.65 }, },
	[163363] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\pissed_01_163363_3585737.ogg]], lengthInSeconds = 2.41 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\pissed_02_163363_3585738.ogg]], lengthInSeconds = 2.04 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\pissed_03_163363_3585739.ogg]], lengthInSeconds = 3.93 }, },
	[159630] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\farewells_01_159630_3584884.ogg]], lengthInSeconds = 3.14 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\farewells_02_159630_3584885.ogg]], lengthInSeconds = 1.69 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\farewells_03_159630_3584886.ogg]], lengthInSeconds = 1.02 }, },
	[159631] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_01_159631_3584887.ogg]], lengthInSeconds = 3.75 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_02_159631_3584888.ogg]], lengthInSeconds = 3.23 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_03_159631_3584889.ogg]], lengthInSeconds = 2.4 }, },
	[159629] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_01_159629_3584881.ogg]], lengthInSeconds = 2.84 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_02_159629_3584882.ogg]], lengthInSeconds = 3.49 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_03_159629_3584883.ogg]], lengthInSeconds = 3.13 }, },
	[159632] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\pissed_01_159632_3584890.ogg]], lengthInSeconds = 3.35 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\pissed_02_159632_3584891.ogg]], lengthInSeconds = 5.98 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\pissed_03_159632_3584892.ogg]], lengthInSeconds = 6.05 }, },
	[159423] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\farewells_01_159423_3488938.ogg]], lengthInSeconds = 3.01 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\farewells_02_159423_3488939.ogg]], lengthInSeconds = 1.41 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\farewells_03_159423_3488940.ogg]], lengthInSeconds = 2.65 }, },
	[159424] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\greetings_01_159424_3488941.ogg]], lengthInSeconds = 2.61 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\greetings_02_159424_3488942.ogg]], lengthInSeconds = 3.38 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\greetings_03_159424_3488943.ogg]], lengthInSeconds = 2.59 }, },
	[159425] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\pissed_01_159425_3488944.ogg]], lengthInSeconds = 2.75 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\pissed_02_159425_3488945.ogg]], lengthInSeconds = 2.67 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bjorn_stouthands\emotions\pissed_03_159425_3488946.ogg]], lengthInSeconds = 3.85 }, },
	[161363] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\emotions\farewells_01_161363_3489612.ogg]], lengthInSeconds = 1.19 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\emotions\farewells_02_161363_3489613.ogg]], lengthInSeconds = 1.54 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\emotions\farewells_03_161363_3489614.ogg]], lengthInSeconds = 1.25 }, },
	[161362] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\emotions\greetings_01_161362_3489615.ogg]], lengthInSeconds = 1.55 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\emotions\greetings_02_161362_3489616.ogg]], lengthInSeconds = 1.32 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\austin_huxworth\emotions\greetings_03_161362_3489617.ogg]], lengthInSeconds = 2.15 }, },
	[158058] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\emotions\farewells_01_158058_3489475.ogg]], lengthInSeconds = .93 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\emotions\farewells_02_158058_3489476.ogg]], lengthInSeconds = 2.72 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\emotions\farewells_03_158058_3489477.ogg]], lengthInSeconds = 2.73 }, },
	[158057] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\emotions\greetings_01_158057_3489478.ogg]], lengthInSeconds = 1.56 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\emotions\greetings_02_158057_3489479.ogg]], lengthInSeconds = 1.23 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\kee-la\emotions\greetings_03_158057_3489480.ogg]], lengthInSeconds = 1.54 }, },
	[169658] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\emotions\farewells_01_169658_3489229.ogg]], lengthInSeconds = 1.73 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\emotions\farewells_02_169658_3489230.ogg]], lengthInSeconds = .94 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\emotions\farewells_03_169658_3489231.ogg]], lengthInSeconds = 1.28 }, },
	[169659] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\emotions\greetings_01_169659_3489232.ogg]], lengthInSeconds = 1.47 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\emotions\greetings_02_169659_3489233.ogg]], lengthInSeconds = .79 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\alaria\emotions\greetings_03_169659_3489234.ogg]], lengthInSeconds = 1.84 }, },
	[158059] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\lana_jordan\emotions\greetings_01_158059_3574367.ogg]], lengthInSeconds = 4.21 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\lana_jordan\emotions\greetings_02_158059_3574368.ogg]], lengthInSeconds = 3.04 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\lana_jordan\emotions\greetings_03_158059_3574369.ogg]], lengthInSeconds = 2.9 }, },
	[158061] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\lana_jordan\emotions\pissed_158061_3574370.ogg]], lengthInSeconds = 3.56 }, },
	[166200] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\emotions\farewells_01_166200_3585777.ogg]], lengthInSeconds = 2.13 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\emotions\farewells_02_166200_3585778.ogg]], lengthInSeconds = 1.04 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\emotions\farewells_03_166200_3585779.ogg]], lengthInSeconds = 1.05 }, },
	[166201] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\emotions\greetings_01_166201_3585780.ogg]], lengthInSeconds = 3.45 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\emotions\greetings_02_166201_3585781.ogg]], lengthInSeconds = 2.75 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\mithdran_dawntracker\emotions\greetings_03_166201_3585782.ogg]], lengthInSeconds = 1.79 }, },
	[159887] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\emotions\farewells_01_159887_3585540.ogg]], lengthInSeconds = 1.32 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\emotions\farewells_02_159887_3585541.ogg]], lengthInSeconds = 1.28 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\emotions\farewells_03_159887_3585542.ogg]], lengthInSeconds = 1 }, },
	[159886] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\emotions\greetings_01_159886_3585543.ogg]], lengthInSeconds = 2.43 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\emotions\greetings_02_159886_3585544.ogg]], lengthInSeconds = 2.41 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\bo\emotions\greetings_03_159886_3585545.ogg]], lengthInSeconds = 2.48 }, },
	[169142] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\emotions\farewells_01_169142_3585522.ogg]], lengthInSeconds = 2.09 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\emotions\farewells_02_169142_3585523.ogg]], lengthInSeconds = 1.38 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\emotions\farewells_03_169142_3585524.ogg]], lengthInSeconds = 1.83 }, },
	[169143] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\emotions\greetings_01_169143_3585525.ogg]], lengthInSeconds = 2.11 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\emotions\greetings_02_169143_3585526.ogg]], lengthInSeconds = 3.28 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\wonsa\emotions\greetings_03_169143_3585527.ogg]], lengthInSeconds = 1.77 }, },
}


voiceOverData.NpcEmotions = {
	[160664] = { Farewells = 169702, Greetings = 169703, Pissed = 169704 },
	[156280] = { Farewells = 154039, Greetings = 154040, Pissed = 154041 },
	[156626] = { Farewells = 154039, Greetings = 154040, Pissed = 154041 },
	[166583] = { Farewells = 163362, Greetings = 163361, Pissed = 163363 },
	[166782] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166573] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[158591] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166805] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166918] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166994] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[175034] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[200657] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166906] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[168431] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166824] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166827] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[166997] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[167021] = { Farewells = 159630, Greetings = 159631, Pissed = 159632 },
	[167145] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167624] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167926] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167212] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167596] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167633] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167675] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167663] = { Farewells = 159630, Greetings = 159629, Pissed = 159632 },
	[167913] = { Farewells = 163362, Greetings = 163361, Pissed = 163363 },
	[171924] = { Farewells = 163362, Greetings = 163361, Pissed = 163363 },
	[167216] = { Farewells = 163362, Greetings = 163361, Pissed = 163363 },
	[166815] = { Farewells = 163362, Greetings = 163361, Pissed = 163363 },
	[166794] = { Greetings = 158059, Pissed = 158061 },
	[166590] = { Farewells = 166200, Greetings = 166201, },
	[166585] = { Farewells = 159887, Greetings = 159886, },
	[175030] = { Farewells = 169142, Greetings = 169143, },
	[157043] = { Farewells = 158058, Greetings = 158057, },
	[157046] = { Farewells = 161363, Greetings = 161362, },
	[157044] = { Farewells = 159423, Greetings = 159424, Pissed = 159425 },
	[175031] = { Farewells = 169658, Greetings = 169659, },
}


voiceOverData.SoundKindIds = {
}


voiceOverData.MuteEmotions = {
	-- 169702
	3488634, 3488635, 3488636,
	-- 169703
	3488637, 3488638, 3488639,
	-- 169704
	3488640, 3488641, 3488642,
	-- 154039
	3485447, 3485448, 3485449,
	-- 154036
	3489790, 3489791,
	-- 154040
	3485450, 3485451, 3485452,
	-- 154037
	3489792, 3489793,
	-- 154038
	3485444, 3485445, 3485446,
	-- 154041
	3485453, 3485454, 3485455,
	-- 163362
	3585731, 3585732, 3585733,
	-- 163361
	3585734, 3585735, 3585736,
	-- 163363
	3585737, 3585738, 3585739,
	-- 159630
	3584884, 3584885, 3584886,
	-- 159631
	3584887, 3584888, 3584889,
	-- 159629
	3584881, 3584882, 3584883,
	-- 159632
	3584890, 3584891, 3584892,
	-- 159423
	3488938, 3488939, 3488940,
	-- 159424
	3488941, 3488942, 3488943,
	-- 159425
	3488944, 3488945, 3488946,
	-- 161363
	3489612, 3489613, 3489614,
	-- 161362
	3489615, 3489616, 3489617,
	-- 158058
	3489475, 3489476, 3489477,
	-- 158057
	3489478, 3489479, 3489480,
	-- 169658
	3489229, 3489230, 3489231,
	-- 169659
	3489232, 3489233, 3489234,
	-- 158059
	3574367, 3574368, 3574369,
	-- 158061
	3574370,
	-- 166200
	3585777, 3585778, 3585779,
	-- 166201
	3585780, 3585781, 3585782,
	-- 159887
	3585540, 3585541, 3585542,
	-- 159886
	3585543, 3585544, 3585545,
	-- 169142
	3585522, 3585523, 3585524,
	-- 169143
	3585525, 3585526, 3585527,
}


voiceOverData.MuteDialogs = {
	-- Captain Garrick
	3485456, 3485457, 3485443, 3485459, 3485460, 3485461,
	-- Private Cole
	3486957, 3486958, 3488623, 3486959, 3486966,
	-- Warlord Breka Grimaxe
	3586023, 3586024, 3586025, 3586026, 3586027, 3586028, 3586029, 3586030, 3586032, 3586034, 3586035, 3586037, 3586038, 3585797, 3584067, 3584039, 3584040, 3584041, 3584042, 3584043, 3584052, 3584053, 3584054, 3584055, 3584056, 3584057, 3584058, 3584059, 3584060, 3584061, 3584072, 3584074, 3584075, 3584077, 3584078, 3584081, 3584082, 3584083, 3584084, 3584085, 3584086, 3584087, 3584089, 3584070, 3584066, 3584069, 3586039, 3586041, 3586042, 3586043,
	-- Grunt Throg
	3586095, 3586096, 3586097, 3586098, 3586099,
	-- Bjorn Stouthands
	3486994, 3488947, 3488948, 3488949, 3488950, 3488951, 3488952,
	-- Austin Huxworth
	3486982, 3486983, 3488692, 3488693, 3486984,
	-- Kee-La
	3486991, 3488806, 3488807, 3488808, 3488809,
	-- Alaria
	3486969, 3486970, 3486971,
	-- Lana Jordan
	3574371,
	-- Mithdran Dawntracker
	3586100, 3586102, 3584222, 3584223, 3586103,
	-- Bo
	3586101,
	-- Won'sa
	3586031, 3586033, 3586036, 3586040,
}


voiceOverData.MuteCinematics = {
	-- 
	3486924, 3486925, 3486926, 3486934, 3584836, 3636985, 3636986, 3636987,
}

ns.VoiceOverData = voiceOverData
