--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

local _, ns = ...;

local voiceOverData = {}

voiceOverData.Cinematics = {
	[1844457017] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152835_3486924.ogg]], lengthInSeconds = 9.75 },
	[3664374311] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152836_3486925.ogg]], lengthInSeconds = 6.25 },
	[1815550003] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152837_3486926.ogg]], lengthInSeconds = 6.05 },
	[2556975142] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152845_3486934.ogg]], lengthInSeconds = 7.6 },
}


voiceOverData.Dialogs = {
	[2598535587] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152731_3485456.ogg]], lengthInSeconds = 3.45 },
	[1922980967] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152732_3485457.ogg]], lengthInSeconds = 5.15 },
	[1090448917] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152718_3485443.ogg]], lengthInSeconds = 6.25 },
	[1929738606] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152734_3485459.ogg]], lengthInSeconds = 5.15 },
	[3687745317] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152846_3486957.ogg]], lengthInSeconds = 2.9 },
	[1655187725] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152847_3486958.ogg]], lengthInSeconds = 3.65 },
	[2911821392] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152897_3488623.ogg]], lengthInSeconds = 1.75 },
	[4229072475] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152848_3486959.ogg]], lengthInSeconds = 5.3 },
	[372028375] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152849_3486966.ogg]], lengthInSeconds = 2.9 },
	[1592247642] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152735_3485460.ogg]], lengthInSeconds = 1.9 },
	[2930961147] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152736_3485461.ogg]], lengthInSeconds = 3.3 },
}


voiceOverData.Emotions = {
	[1] = {
		Greetings = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_01_169703_3488637.ogg]], lengthInSeconds = 1.55 },[2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_02_169703_3488638.ogg]], lengthInSeconds = 1.35 },[3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_03_169703_3488639.ogg]], lengthInSeconds = 2.3 },},
		Pissed = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_01_169704_3488640.ogg]], lengthInSeconds = 2.3 },[2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_02_169704_3488641.ogg]], lengthInSeconds = 2.65 },[3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_03_169704_3488642.ogg]], lengthInSeconds = 2.05 },},
		Farewells = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_01_169702_3488634.ogg]], lengthInSeconds = 1.2 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_02_169702_3488635.ogg]], lengthInSeconds = 1.55 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_03_169702_3488636.ogg]], lengthInSeconds = 1.1 }, }
	},
	[2] = {
		Greetings = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154040_3485450.ogg]], lengthInSeconds = 2.1 },[2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154040_3485451.ogg]], lengthInSeconds = 2.25 },[3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_03_154040_3485452.ogg]], lengthInSeconds = 1.75 },},
		Pissed = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_01_154041_3485453.ogg]], lengthInSeconds = 3 },[2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_02_154041_3485454.ogg]], lengthInSeconds = 3.4 },[3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_03_154041_3485455.ogg]], lengthInSeconds = 6.4 },},
		Farewells = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_01_154039_3485447.ogg]], lengthInSeconds = 2.45 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_02_154039_3485448.ogg]], lengthInSeconds = 1.9 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_03_154039_3485449.ogg]], lengthInSeconds = 1.6 }, }
	},
	[3] = {
		Greetings = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154037_3489792.ogg]], lengthInSeconds = 1.4 },[2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154037_3489793.ogg]], lengthInSeconds = 1.35 },[3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154038_3485444.ogg]], lengthInSeconds = 3.65 },[4] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154038_3485445.ogg]], lengthInSeconds = 2.55 },[5] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_03_154038_3485446.ogg]], lengthInSeconds = 2.2 },},
		Pissed = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_01_154041_3485453.ogg]], lengthInSeconds = 3 },[2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_02_154041_3485454.ogg]], lengthInSeconds = 6.4 },[3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_03_154041_3485455.ogg]], lengthInSeconds = 3.4 },},
		Farewells = { [1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_01_154036_3489790.ogg]], lengthInSeconds = 1.2 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_02_154036_3489791.ogg]], lengthInSeconds = 1 }, }
	},
}


voiceOverData.NpcEmotions = {
	[160664] = 1,
	[157051] = 1,
	[156280] = 2,
	[156626] = 2,
}


voiceOverData.SoundKindIds = {
}


voiceOverData.MuteEmotions = {
	-- 1
	3488634, 3488635, 3488636, 3488637, 3488638, 3488639, 3488640, 3488641, 3488642,
	-- 2
	3485447, 3485448, 3485449, 3485450, 3485451, 3485452, 3485453, 3485454, 3485455,
	-- 3
	3489790, 3489791, 3489792, 3489793, 3485444, 3485445, 3485446, 3485453, 3485454, 3485455,
}


voiceOverData.MuteDialogs = {
	-- 
	3486924, 3486925, 3486926, 3486934,
	-- Captain Garrick
	3485456, 3485457, 3485443, 3485459, 3485460, 3485461,
	-- Private Cole
	3486957, 3486958, 3488623, 3486959, 3486966,
}

ns.VoiceOverData = voiceOverData
