--[[
    WARNING: This file is automatically generated. DO NOT modify this file manually, as your changes will be lost the next time this file is regenerated.
    Instead, modify the source files used to generate this file, and then regenerate the file using the appropriate tool.
]]

local _, ns = ...;

local voiceOverData = {}

voiceOverData.Cinematics = {
	[1844457017] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152835_3486924.ogg]], lengthInSeconds = 9.75 },
	[3664374311] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152836_3486925.ogg]], lengthInSeconds = 6.25 },
	[1815550003] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152837_3486926.ogg]], lengthInSeconds = 6.05 },
	[2556975142] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_alliance_begin\vo_152845_3486934.ogg]], lengthInSeconds = 7.6 },
	[706583598] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_156812_3584836.ogg]], lengthInSeconds = 10.86 },
	[2768331800] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_161221_3636985.ogg]], lengthInSeconds = 6.83 },
	[2448792133] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_161222_3636986.ogg]], lengthInSeconds = 6.43 },
	[2713478487] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\cinematics\exiles_rich_hord_begin\vo_161223_3636987.ogg]], lengthInSeconds = 6.38 },
}


voiceOverData.Dialogs = {
	[2598535587] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152731_3485456.ogg]], lengthInSeconds = 3.45 },
	[1922980967] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152732_3485457.ogg]], lengthInSeconds = 5.15 },
	[1090448917] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152718_3485443.ogg]], lengthInSeconds = 6.25 },
	[1929738606] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152734_3485459.ogg]], lengthInSeconds = 5.15 },
	[3687745317] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152846_3486957.ogg]], lengthInSeconds = 2.9 },
	[1655187725] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152847_3486958.ogg]], lengthInSeconds = 3.65 },
	[2911821392] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152897_3488623.ogg]], lengthInSeconds = 1.75 },
	[4229072475] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152848_3486959.ogg]], lengthInSeconds = 5.3 },
	[372028375] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\vo_152849_3486966.ogg]], lengthInSeconds = 2.9 },
	[1592247642] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152735_3485460.ogg]], lengthInSeconds = 1.9 },
	[2930961147] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\vo_152736_3485461.ogg]], lengthInSeconds = 3.3 },
	[2014878743] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156949_3586023.ogg]], lengthInSeconds = 3.94 },
	[214564778] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156950_3586024.ogg]], lengthInSeconds = 8.02 },
	[189554568] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156951_3586025.ogg]], lengthInSeconds = 7.19 },
	[4153089120] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156952_3586026.ogg]], lengthInSeconds = 5.33 },
	[3743913128] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156973_3586095.ogg]], lengthInSeconds = 4.55 },
	[2374790243] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156974_3586096.ogg]], lengthInSeconds = 3.48 },
	[122125822] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156975_3586097.ogg]], lengthInSeconds = 2.18 },
	[3051315049] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156976_3586098.ogg]], lengthInSeconds = 6.13 },
	[2623088084] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\vo_156977_3586099.ogg]], lengthInSeconds = 3.72 },
	[4279207447] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156953_3586027.ogg]], lengthInSeconds = 1.93 },
	[1466862686] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\vo_156954_3586028.ogg]], lengthInSeconds = 4.81 },
}


voiceOverData.Emotions = {
	[1] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_01_169702_3488634.ogg]], lengthInSeconds = 1.2 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_02_169702_3488635.ogg]], lengthInSeconds = 1.55 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\farewells_03_169702_3488636.ogg]], lengthInSeconds = 1.1 }, },
	[2] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_01_169703_3488637.ogg]], lengthInSeconds = 1.55 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_02_169703_3488638.ogg]], lengthInSeconds = 1.35 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\greetings_03_169703_3488639.ogg]], lengthInSeconds = 2.3 }, },
	[3] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_01_169704_3488640.ogg]], lengthInSeconds = 2.3 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_02_169704_3488641.ogg]], lengthInSeconds = 2.65 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\private_cole\emotions\pissed_03_169704_3488642.ogg]], lengthInSeconds = 2.05 }, },
	[4] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_01_154039_3485447.ogg]], lengthInSeconds = 2.45 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_02_154039_3485448.ogg]], lengthInSeconds = 1.9 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_03_154039_3485449.ogg]], lengthInSeconds = 1.6 }, },
	[5] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_01_154036_3489790.ogg]], lengthInSeconds = 1.2 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\farewells_02_154036_3489791.ogg]], lengthInSeconds = 1 }, },
	[6] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154040_3485450.ogg]], lengthInSeconds = 2.1 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154040_3485451.ogg]], lengthInSeconds = 2.25 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_03_154040_3485452.ogg]], lengthInSeconds = 1.75 }, },
	[7] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154037_3489792.ogg]], lengthInSeconds = 1.4 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154037_3489793.ogg]], lengthInSeconds = 1.35 }, },
	[8] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_01_154038_3485444.ogg]], lengthInSeconds = 3.65 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_02_154038_3485445.ogg]], lengthInSeconds = 2.55 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\greetings_03_154038_3485446.ogg]], lengthInSeconds = 2.2 }, },
	[9] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_01_154041_3485453.ogg]], lengthInSeconds = 3 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_02_154041_3485454.ogg]], lengthInSeconds = 3.4 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\captain_garrick\emotions\pissed_03_154041_3485455.ogg]], lengthInSeconds = 6.4 }, },
	[10] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\farewells_01_163362_3585731.ogg]], lengthInSeconds = .96 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\farewells_02_163362_3585732.ogg]], lengthInSeconds = 1.28 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\farewells_03_163362_3585733.ogg]], lengthInSeconds = 2.38 }, },
	[11] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\greetings_01_163361_3585734.ogg]], lengthInSeconds = 1.6 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\greetings_02_163361_3585735.ogg]], lengthInSeconds = 1.97 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\greetings_03_163361_3585736.ogg]], lengthInSeconds = 2.65 }, },
	[12] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\pissed_01_163363_3585737.ogg]], lengthInSeconds = 2.41 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\pissed_02_163363_3585738.ogg]], lengthInSeconds = 2.04 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\grunt_throg\emotions\pissed_03_163363_3585739.ogg]], lengthInSeconds = 3.93 }, },
	[13] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\farewells_01_159630_3584884.ogg]], lengthInSeconds = 3.14 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\farewells_02_159630_3584885.ogg]], lengthInSeconds = 1.69 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\farewells_03_159630_3584886.ogg]], lengthInSeconds = 1.02 }, },
	[14] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_01_159631_3584887.ogg]], lengthInSeconds = 3.75 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_02_159631_3584888.ogg]], lengthInSeconds = 3.23 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_03_159631_3584889.ogg]], lengthInSeconds = 2.4 }, },
	[15] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_01_159629_3584881.ogg]], lengthInSeconds = 2.84 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_02_159629_3584882.ogg]], lengthInSeconds = 3.49 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\greetings_03_159629_3584883.ogg]], lengthInSeconds = 3.13 }, },
	[16] = {
		[1] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\pissed_01_159632_3584890.ogg]], lengthInSeconds = 3.35 }, [2] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\pissed_02_159632_3584891.ogg]], lengthInSeconds = 5.98 }, [3] = { file =[[Interface\AddOns\WowUkrainizer\assets\sounds\creatures\warlord_breka_grimaxe\emotions\pissed_03_159632_3584892.ogg]], lengthInSeconds = 6.05 }, },
}


voiceOverData.NpcEmotions = {
	[160664] = { Farewells = 1, Greetings = 2, Pissed = 3 },
	[156280] = { Farewells = 4, Greetings = 6, Pissed = 9 },
	[156626] = { Farewells = 4, Greetings = 6, Pissed = 9 },
	[166583] = { Farewells = 10, Greetings = 11, Pissed = 12 },
	[166782] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166573] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[158591] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166805] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166918] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166994] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[175034] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[200657] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166906] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[168431] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166824] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166827] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[166997] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[167021] = { Farewells = 13, Greetings = 14, Pissed = 16 },
	[167145] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167624] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167926] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167212] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167596] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167633] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167675] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167663] = { Farewells = 13, Greetings = 15, Pissed = 16 },
	[167913] = { Farewells = 10, Greetings = 11, Pissed = 12 },
	[171924] = { Farewells = 10, Greetings = 11, Pissed = 12 },
	[167216] = { Farewells = 10, Greetings = 11, Pissed = 12 },
	[166815] = { Farewells = 10, Greetings = 11, Pissed = 12 },
	[166784] = { Farewells = 10, Greetings = 11, Pissed = 12 },
}


voiceOverData.SoundKindIds = {
}


voiceOverData.MuteEmotions = {
	-- 1
	3488634, 3488635, 3488636,
	-- 2
	3488637, 3488638, 3488639,
	-- 3
	3488640, 3488641, 3488642,
	-- 4
	3485447, 3485448, 3485449,
	-- 5
	3489790, 3489791,
	-- 6
	3485450, 3485451, 3485452,
	-- 7
	3489792, 3489793,
	-- 8
	3485444, 3485445, 3485446,
	-- 9
	3485453, 3485454, 3485455,
	-- 10
	3585731, 3585732, 3585733,
	-- 11
	3585734, 3585735, 3585736,
	-- 12
	3585737, 3585738, 3585739,
	-- 13
	3584884, 3584885, 3584886,
	-- 14
	3584887, 3584888, 3584889,
	-- 15
	3584881, 3584882, 3584883,
	-- 16
	3584890, 3584891, 3584892,
}


voiceOverData.MuteDialogs = {
	-- Captain Garrick
	3485456, 3485457, 3485443, 3485459, 3485460, 3485461,
	-- Private Cole
	3486957, 3486958, 3488623, 3486959, 3486966,
	-- Warlord Breka Grimaxe
	3586023, 3586024, 3586025, 3586026, 3586027, 3586028,
	-- Grunt Throg
	3586095, 3586096, 3586097, 3586098, 3586099,
}


voiceOverData.MuteCinematics = {
	-- 
	3486924, 3486925, 3486926, 3486934,
	-- 
	3584836, 3636985, 3636986, 3636987,
}

ns.VoiceOverData = voiceOverData
