name: Build Artifact

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 200
          
      - name: Generate Changelog
        run: ./generate_changelog.sh
        
      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -d -z

      - uses: actions/upload-artifact@v3
        with:
          name: WowUkrainizer-DEV#${{ github.sha }}
          path: .release/