name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create_release:
    name: Create and Deploy Pre-release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update AddOn Version
        id: addon_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "v${major}.${minor}.${patch}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "/^(?!doc|chore|ci|build|refactor)/"

      - name: Check Versions
        id: check_version_changed
        run: |
          echo "ADDON_VERSION_CHANGED=${{ steps.bump_addon_version.outputs.version != format('v{0}', steps.bump_addon_version.outputs.previous_version) }}" >> "$GITHUB_OUTPUT"
          echo "Current Version: ${{ steps.bump_addon_version.outputs.previous_version }}"
          echo "New Version: ${{ steps.bump_addon_version.outputs.version }}"

      - name: Create GitHub Release
        id: create_guthub_release
        if: "${{ steps.check_version_changed.outputs.ADDON_VERSION_CHANGED == 'true' }}"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.addon_version.outputs.version }}
          name: ${{ steps.addon_version.outputs.version }}
          prerelease: false

      - name: Trigger workflow to publish new version
        if: "${{ steps.check_version_changed.outputs.ADDON_VERSION_CHANGED == 'true' }}"
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Cancri55E/WowUkrainizer/actions/workflows/package.yml/dispatches \
          -d '{"ref":"master"}'
