name: Create release and push to CurseForge

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push_to_curseforge:
    name: Push Release to CurseForge
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'develop'
          fetch-depth: 0

      - name: Set execute permissions
        run: chmod +x generate_changelog.sh
  
      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
