name: Build and Deploy Package

on:
  workflow_dispatch:

jobs:
  package:
    name: Create and Deploy Package
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Checkout DevTools
        uses: actions/checkout@v4
        with:
          ref: feature/refactoring
          repository: Cancri55E/WowUkrainizer-DevTools
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: DevTools

      - name: Checkout RawData
        uses: actions/checkout@v4
        with:
          ref: main
          repository: Cancri55E/WowUkrainizer-Data
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: RawData

      - name: Restore DevTools NuGet packages
        run: dotnet restore ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj

      - name: Build DevTools project
        run: dotnet build ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj --configuration Release --no-restore

      - name: Run DevTools project
        id: run_update_translation_cmd
        run: |
          dotnet run --project ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj --configuration Release --mode "generate-lua" --connectionString "${{ secrets.MAIN_DB_CONNECTION_STRING }} --folder "${{ github.workspace }}/Database" --gameClientConnectionString "${{ secrets.MONGODB_CONNECTION_STRING }}" 2>log.txt

      - name: Display update translation log
        run: |
          cat log.txt

      - name: Generate CHANGELOG.md
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Deploy AddOn
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
