name: Push alpha to CurseForge

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  push_alpha_to_curseforge:
    name: Push to CurseForge
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Checkout DevTools
        uses: actions/checkout@master
        with:
          ref: feature/refactoring
          repository: Cancri55E/WowUkrainizer-DevTools
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: DevTools

      - name: Checkout RawData
        uses: actions/checkout@master
        with:
          ref: main
          repository: Cancri55E/WowUkrainizer-Data
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: RawData

      - name: Restore DevTools NuGet packages
        run: dotnet restore ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj

      - name: Build DevTools project
        run: dotnet build ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj --configuration Release --no-restore

      - name: Run DevTools project
        id: run_update_translation_cmd
        run: |
          dotnet run --project ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj --configuration Release -- --m "generate-lua" --ds "${{ github.workspace }}/RawData/Data.db" --l "${{ github.workspace }}/Database" 2>log.txt

      - name: Display update translation log
        run: |
          cat log.txt
          
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
